### ISSUE TITLE
Clarification on formioService

### ISSUE THREAD

**Issue by anupriyaideas2it** [formio/ng2-formio#57]
1)What is the purpose of adding an attribute called SERVICE in formio tag?
'<formio src="test.json" `service="?"></formio>'
2)Is there any working example using attribute SERVICE in formio tag?
3)Is it possible to invoke a custom function while loading a form ?,Without disturbing formioService
I.e.,  i want to preprocess the json and  also want to perform some preaction.
4)Is it Possible to extend the FormioService? In order to customize the action on the event
5)Wizard not rendered while giving json in API (src) format .

**Comment by travist** [comment]
@anupriyaideas2it The idea of the service parameter is that you can extend the ```FormioService``` class, and then pass that into the directive so that it uses your extended class vs. the core service. This allows you to do some more flexible things to inject your custom logic within the Service functions. I think that answers 1-4.

5 sounds like a bug, and I will look into it.

Thanks,

Travis.
